# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards

replicaCount: 1

image:
  repository: eazybytes/cards
  tag: latest

containerPort: 9092

service:
  type: LoadBalancer
  port: 9092
  targetPort: 9092

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true